version: 2.1

jobs:
  build-builder-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name:    "Run Docker build"
          command: "docker build ./env -t kuklinistvan
          /qemu_spice_el9_builder:latest"
      - run:
          name:    "Push to repository"
          command: "docker login --username=kuklinistvan --password=$MY_DOCKER_API_TOKEN docker.io && docker push kuklinistvan
          qemu_spice_el9_builder:latest"

  build-capstone:
    docker:
      - image: kuklinistvan/qemu_spice_el9_builder
    steps:
      - checkout
      - run:
          name:    "Build capstone"
          command: "bash jobs/port_capstone_devel/build.sh"
      - store_artifacts:
          path: rpmbuild/RPMS/
      - store_artifacts:
          path: rpmbuild/SRPMS/
        
  
workflows:
  all:
    jobs:
      - build-builder-image
      - build-capstone
